---
  name: 'CNN'
  verbosity: 0
  no_epochs: 300
  loss_function_name: 'MSE'
  split_validation: 0.2
  test_size: 0.2
  random_state: 0
  early_stopping_patience: 20
  early_stopping: True
  early_stopping_monitor: 'val_loss'
  restore_best_weights: True
  metrics: 
    - 'MSE'
    - 'RMSE'
  model: None
  shuffle_data: False
...